"use client";
import {useCallback,useEffect,useState} from 'react';
const blank=()=>({title:'',kind:'mcq',source_id:'',instructions:'',center_id:'',open_at:'',close_at:'',duration_min:60,attempts_allowed:1,pass_mark:50,shuffle_questions:true,shuffle_options:false,allow_back:true,show_score:false,show_answers:false,access_code:''});
const status={draft:'ร่าง',open:'เปิดสอบ',closed:'ปิดแล้ว',in_progress:'กำลังทำ',submitted:'ส่งแล้ว',awaiting_grade:'รอตรวจ MEQ',graded:'ตรวจแล้ว'};
function csvCell(value){const text=String(value??'');return '"'+(/^[=+\-@\t\r]/.test(text)?"'":'')+text.replaceAll('"','""')+'"';}
export default function DeliveryManager({sb}){
 const [rows,setRows]=useState([]),[sources,setSources]=useState({mcq:[],meq:[]}),[centers,setCenters]=useState([]),[form,setForm]=useState(null);
 const [selected,setSelected]=useState(null),[roster,setRoster]=useState([]),[grading,setGrading]=useState(null),[grades,setGrades]=useState({});
 const [busy,setBusy]=useState(false),[loading,setLoading]=useState(true),[error,setError]=useState(''),[message,setMessage]=useState('');
 const rpc=useCallback(async(action,payload={})=>{const {data,error}=await sb.rpc('delivery_manage',{action,payload});if(error)throw Error(error.message);return data;},[sb]);
 const load=useCallback(async()=>{setLoading(true);try{
  const [list,mcq,meq,c]=await Promise.all([rpc('list'),sb.from('exam_sets').select('id,name,status').order('updated_at',{ascending:false}),sb.from('meq_cases').select('id,title').order('updated_at',{ascending:false}),sb.from('medical_centers').select('id,name').order('name')]);
  for(const r of [mcq,meq,c])if(r.error)throw Error(r.error.message);
  setRows(list);setSources({mcq:mcq.data||[],meq:meq.data||[]});setCenters(c.data||[]);
 }catch(e){setError(e.message);}finally{setLoading(false);}},[sb,rpc]);
 useEffect(()=>{load();},[load]);
 const run=async(fn)=>{setBusy(true);setError('');setMessage('');try{await fn();}catch(e){setError(e.message);}finally{setBusy(false);}};
 const open=e=>run(async()=>{setSelected(e);setForm(null);setGrading(null);setRoster(await rpc('roster',{id:e.id}));});
 const create=event=>{event.preventDefault();run(async()=>{
  if(!form.source_id)throw Error('เลือกชุดข้อสอบหรือเคสก่อนบันทึก');
  if(form.open_at&&form.close_at&&new Date(form.close_at)<=new Date(form.open_at))throw Error('เวลาปิดต้องอยู่หลังเวลาเปิด');
  const data=await rpc('create',{...form,open_at:form.open_at?new Date(form.open_at).toISOString():null,close_at:form.close_at?new Date(form.close_at).toISOString():null});
  setForm(null);setSelected(data);setRoster([]);await load();setMessage('บันทึกร่างแล้ว ยังไม่เปิดให้ผู้สอบเข้าทำ');
 });};
 const changeStatus=action=>run(async()=>{
  if(action==='publish'&&!window.confirm('ยืนยันเปิดรอบสอบนี้? ระบบจะตรึงฉบับข้อสอบและเปิดให้ผู้มีสิทธิ์ตามเวลาที่ตั้งไว้'))return;
  if(action==='close'&&!window.confirm('ปิดรับผู้เข้าสอบใหม่? ผู้ที่เริ่มแล้วจะทำต่อได้จนหมดเวลาของตน'))return;
  await rpc(action,{id:selected.id});const fresh=await rpc('list');setRows(fresh);setSelected(fresh.find(x=>x.id===selected.id));setMessage(action==='publish'?'เปิดรอบสอบแล้ว':'ปิดรับผู้เข้าสอบใหม่แล้ว');
 });
 const review=id=>run(async()=>{const data=await rpc('review',{attempt_id:id});setGrading(data);setGrades(data.grades||{});});
 const saveGrades=event=>{event.preventDefault();run(async()=>{await rpc('grade',{attempt_id:grading.id,revision:grading.revision,grades});setGrading(null);setRoster(await rpc('roster',{id:selected.id}));setMessage('บันทึกผลตรวจ MEQ แล้ว');});};
 const exportCsv=()=>{const lines=[['ผู้สอบ','รหัส','ครั้งที่','สถานะ','คะแนน','คะแนนเต็ม','เริ่ม','ส่ง'],...roster.map(r=>[r.name,r.student_id,r.attempt_no,status[r.status],r.score,r.max_score,r.started_at,r.submitted_at])];const url=URL.createObjectURL(new Blob(['\uFEFF'+lines.map(row=>row.map(csvCell).join(',')).join('\r\n')],{type:'text/csv;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download='ผลสอบ.csv';a.click();URL.revokeObjectURL(url);};
 const set=(k,v)=>setForm(f=>({...f,[k]:v}));
 return <div className="delivery"><header className="delivery-heading"><div><h1>จัดรอบสอบ</h1><p>เลือกชุดข้อสอบ ตั้งค่าการสอบ และติดตามผล</p></div><button className="btn" disabled={busy} onClick={()=>{setForm(blank());setSelected(null);setGrading(null);setError('');}}>สร้างรอบสอบ</button></header>{error&&<div role="alert" className="delivery-alert">{error}<button className="btn ghost sm" onClick={load}>โหลดข้อมูลอีกครั้ง</button></div>}{message&&<p role="status" className="delivery-sync">{message}</p>}
 {form?<form className="delivery-paper delivery-form" onSubmit={create}><h2>สร้างรอบสอบใหม่</h2><fieldset disabled={busy}><legend>ข้อสอบและคำชี้แจง</legend><label>ชื่อรอบสอบ<input required maxLength={300} value={form.title} onChange={e=>set('title',e.target.value)}/></label><div className="grid2"><label>รูปแบบ<select value={form.kind} onChange={e=>setForm(f=>({...f,kind:e.target.value,source_id:''}))}><option value="mcq">MCQ · เลือกคำตอบ</option><option value="meq">MEQ · เปิดทีละตอน</option></select></label><label>{form.kind==='mcq'?'ชุดข้อสอบ':'เคส MEQ'}<select required value={form.source_id} onChange={e=>set('source_id',e.target.value)}><option value="">เลือกจากคลัง</option>{sources[form.kind].map(s=><option key={s.id} value={s.id}>{s.name||s.title}{s.status?` (${s.status==='ready'?'พร้อมใช้':'ร่าง'})`:''}</option>)}</select></label></div>{!sources[form.kind].length&&<p>คลังยังว่าง กรุณาสร้าง{form.kind==='mcq'?'ชุด MCQ':'เคส MEQ'}ก่อน รอบนี้ยังไม่ได้นำข้อสอบเก่าเข้า</p>}<label>คำชี้แจงก่อนสอบ<textarea rows={4} value={form.instructions} onChange={e=>set('instructions',e.target.value)}/></label></fieldset>
 <fieldset disabled={busy}><legend>ผู้มีสิทธิ์และเวลาสอบ</legend><label>กลุ่มผู้สอบ<select value={form.center_id} onChange={e=>set('center_id',e.target.value)}><option value="">ผู้เข้าสู่ระบบทุกศูนย์</option>{centers.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label><div className="grid2"><label>เวลาเปิด<input type="datetime-local" value={form.open_at} onChange={e=>set('open_at',e.target.value)}/></label><label>เวลาสิ้นสุดรอบสอบ<input type="datetime-local" value={form.close_at} onChange={e=>set('close_at',e.target.value)}/></label></div><p>เวลาตามเครื่องของคุณ ผู้สอบทุกคนต้องส่งไม่เกินเวลาสิ้นสุดรอบสอบ</p><div className="grid3"><label>เวลาทำ (นาที)<input required disabled={form.kind==='meq'} type="number" min="1" max="1440" step="1" value={form.duration_min} onChange={e=>set('duration_min',e.target.value)}/></label><label>จำนวนครั้ง<input required type="number" min="1" max="100" step="1" value={form.attempts_allowed} onChange={e=>set('attempts_allowed',e.target.value)}/></label><label>เกณฑ์ผ่าน (%)<input required type="number" min="0" max="100" step="0.01" value={form.pass_mark} onChange={e=>set('pass_mark',e.target.value)}/></label></div>{form.kind==='meq'&&<p>MEQ ใช้เวลาของแต่ละตอนจากเคส ระบบรวมเวลาให้อัตโนมัติเมื่อเปิดรอบสอบ</p>}<label>รหัสเข้าสอบ (เว้นว่างได้)<input autoComplete="off" maxLength={100} value={form.access_code} onChange={e=>set('access_code',e.target.value)}/></label></fieldset>
 <fieldset disabled={busy}><legend>ระหว่างสอบและหลังส่ง</legend>{form.kind==='mcq'&&<><label className="delivery-check"><input type="checkbox" checked={form.shuffle_questions} onChange={e=>set('shuffle_questions',e.target.checked)}/>สลับลำดับข้อ</label><label className="delivery-check"><input type="checkbox" checked={form.shuffle_options} onChange={e=>set('shuffle_options',e.target.checked)}/>สลับตัวเลือก</label><label className="delivery-check"><input type="checkbox" checked={form.allow_back} onChange={e=>set('allow_back',e.target.checked)}/>ย้อนกลับแก้คำตอบได้</label></>}{form.kind==='meq'&&<p>MEQ เปิดทีละตอนและล็อกตอนก่อนหน้า ไม่สลับโจทย์</p>}<label className="delivery-check"><input type="checkbox" checked={form.show_score} onChange={e=>set('show_score',e.target.checked)}/>แสดงคะแนนหลังส่ง / ตรวจเสร็จ</label><label className="delivery-check"><input type="checkbox" checked={form.show_answers} onChange={e=>set('show_answers',e.target.checked)}/>เปิดเฉลยหลังส่ง / ตรวจเสร็จ</label><p>การตั้งค่าจะตรึงเมื่อเปิดรอบสอบ เพื่อให้ผู้สอบใช้เงื่อนไขเดียวกัน</p></fieldset><div className="delivery-actions"><button type="button" className="btn ghost" disabled={busy} onClick={()=>setForm(null)}>ยกเลิก</button><button className="btn" disabled={busy}>บันทึกร่าง</button></div></form>:
 grading?<form className="delivery-paper" onSubmit={saveGrades}><h2>ตรวจคำตอบ MEQ</h2><p>ให้คะแนนแต่ละคำถามตามเกณฑ์ แล้วบันทึกผลตรวจ</p>{grading.paper.map((s,i)=><section key={i} className="delivery-grading-stage"><h3>ตอนที่ {i+1}: {s.title}</h3><p className="delivery-text">{s.scenario}</p>{s.questions.map(q=><div key={q.id} className="delivery-grade-question"><h3>{q.prompt}</h3><p className="delivery-text">คำตอบผู้สอบ: {grading.answers[q.id]||'ไม่ได้ตอบ'}</p><details><summary>แนวคำตอบและเกณฑ์คะแนน</summary><p className="delivery-text">{q.modelAnswer}</p><p className="delivery-text">{q.rubric}</p></details><div className="grid2"><label>คะแนน (เต็ม {q.points})<input required type="number" min="0" max={q.points} step="0.01" disabled={busy} value={grades[q.id]?.points??''} onChange={e=>setGrades(g=>({...g,[q.id]:{...g[q.id],points:e.target.value}}))}/></label><label>ข้อเสนอแนะ<input disabled={busy} value={grades[q.id]?.comment||''} onChange={e=>setGrades(g=>({...g,[q.id]:{...g[q.id],comment:e.target.value}}))}/></label></div></div>)}</section>)}<div className="delivery-actions"><button type="button" className="btn ghost" disabled={busy} onClick={()=>setGrading(null)}>กลับ</button><button className="btn" disabled={busy}>บันทึกผลตรวจ</button></div></form>:
 selected?<section className="delivery-paper"><button className="btn ghost sm" onClick={()=>setSelected(null)}>กลับรายการรอบสอบ</button><h2>{selected.title}</h2><p>{selected.kind.toUpperCase()} · {status[selected.status]} · {selected.duration_min} นาที · {selected.attempts_allowed} ครั้ง · เกณฑ์ผ่าน {selected.pass_mark}%</p><p>การย้อนกลับ: {selected.allow_back?'อนุญาต':'ไม่อนุญาต'} · คะแนน: {selected.show_score?'แสดง':'ซ่อน'} · เฉลย: {selected.show_answers?'เปิด':'ปิด'}</p><p className="delivery-text">{selected.instructions}</p><div className="row">{selected.status!=='open'?<button className="btn" disabled={busy} onClick={()=>changeStatus('publish')}>เปิดรอบสอบ</button>:<button className="btn danger" disabled={busy} onClick={()=>changeStatus('close')}>ปิดรับผู้สอบใหม่</button>}<button className="btn ghost" disabled={busy} onClick={()=>open(selected)}>รีเฟรชผู้สอบ</button><button className="btn ghost" disabled={!roster.length} onClick={exportCsv}>ส่งออกผล CSV</button></div><h3 className="delivery-subheading">ผู้เข้าสอบ {roster.length} ครั้ง · รอตรวจ {roster.filter(x=>x.status==='awaiting_grade').length}</h3><div className="tablewrap"><table><thead><tr><th>ผู้สอบ</th><th>ครั้งที่</th><th>สถานะ</th><th>คะแนน</th><th>ตรวจคำตอบ</th></tr></thead><tbody>{!roster.length?<tr><td colSpan="5">ยังไม่มีผู้เข้าสอบ</td></tr>:roster.map(r=><tr key={r.id}><td>{r.name||r.student_id||'ผู้สอบ'}</td><td>{r.attempt_no}</td><td>{r.status==='in_progress'&&new Date(r.expires_at)<new Date()?'หมดเวลา · รอผู้สอบเชื่อมต่อเพื่อสรุปผล':status[r.status]}</td><td>{r.score==null?'—':`${r.score}/${r.max_score}`}</td><td>{selected.kind==='meq'&&r.status!=='in_progress'&&<button className="btn ghost sm" disabled={busy} onClick={()=>review(r.id)}>ตรวจ MEQ</button>}</td></tr>)}</tbody></table></div></section>:
 loading?<p role="status">กำลังโหลดรอบสอบ…</p>:!rows.length?<section className="delivery-paper"><h2>ยังไม่มีรอบสอบ</h2><p>สร้างชุด MCQ หรือเคส MEQ ในคลังก่อน จากนั้นสร้างรอบสอบเพื่อตั้งเวลาและผู้มีสิทธิ์</p></section>:<div className="delivery-list">{rows.map(e=><article className="delivery-row" key={e.id}><div><h2>{e.title}</h2><p>{e.kind.toUpperCase()} · {status[e.status]} · {e.duration_min} นาที</p></div><button className="btn ghost" disabled={busy} onClick={()=>open(e)}>ตั้งค่าและผลสอบ</button></article>)}</div>}
 </div>;
}
