"use client";
import {useState,useEffect,useId} from 'react';
import Bank from './Bank';
import {summarizeMeq,reviewMeq,validateMeq,newCase,newStage,newQuestion} from '../lib/meq.mjs';
import {parseMeqMarkdown} from '../lib/meqMarkdown.mjs';
function Field({label,area=false,...props}){const id=useId();return <div className="field"><label htmlFor={id}>{label}</label>{area?<textarea id={id} {...props}/>:<input id={id} {...props}/>}</div>}
export default function MeqBank({sb,bp,me,canWrite,canApprove,notify,previewCases=null}){
 const [rows,setRows]=useState(previewCases||[]),[loading,setLoading]=useState(!previewCases),[error,setError]=useState(''),[search,setSearch]=useState(''),[editing,setEditing]=useState(null),[active,setActive]=useState(0),[dirty,setDirty]=useState(false),[busy,setBusy]=useState(false),[legacy,setLegacy]=useState(false);
 const [fYear,setFYear]=useState(''),[fOpen,setFOpen]=useState(''),[sortBy,setSortBy]=useState('az');
 const load=async()=>{if(previewCases)return;setLoading(true);setError('');try{const {data,error}=await sb.from('meq_cases').select('*').order('updated_at',{ascending:false});if(error)throw error;setRows(data||[]);}catch{setError('โหลดคลัง MEQ ไม่สำเร็จ กรุณาลองใหม่');}finally{setLoading(false)}};
 useEffect(()=>{load();},[sb]);
 useEffect(()=>{if(!dirty)return;const warn=e=>{e.preventDefault();e.returnValue=''};window.addEventListener('beforeunload',warn);return()=>window.removeEventListener('beforeunload',warn)},[dirty]);
 const open=row=>{setEditing(structuredClone(row));setDirty(false);setActive(0);setError('')};
 const close=()=>{if(busy)return;if(dirty&&!confirm('ยังไม่ได้บันทึก ต้องการทิ้งการแก้ไขและกลับคลังหรือไม่?'))return;setEditing(null);setDirty(false)};
 const update=patch=>{setEditing(x=>({...x,...patch}));setDirty(true)};
 const docUpdate=patch=>update({document:{...editing.document,...patch}});
 const stageUpdate=patch=>docUpdate({stages:editing.document.stages.map((s,i)=>i===active?{...s,...patch}:s)});
 const save=async()=>{const problem=validateMeq(editing);if(problem){setError(problem);return}setBusy(true);setError('');try{
 if(previewCases){setRows(old=>editing.id?old.map(r=>r.id===editing.id?structuredClone(editing):r):[...old,{...structuredClone(editing),id:crypto.randomUUID()}]);}
 else{const payload={title:editing.title.trim(),academic_year:Number(editing.academic_year),exam_year:editing.exam_year?Number(editing.exam_year):null,document:editing.document,updated_at:new Date().toISOString()};let q=editing.id?sb.from('meq_cases').update(payload).eq('id',editing.id).eq('updated_at',editing.updated_at):sb.from('meq_cases').insert({...payload,author_id:me});const {data,error}=await q.select('id');if(error)throw error;if(!data?.length)throw Error('conflict');await load();}
 setDirty(false);setEditing(null);notify?.(previewCases?'บันทึกตัวอย่างในหน้านี้แล้ว (รีเฟรชแล้วคืนค่า)':'บันทึกเคส MEQ แล้ว');
 }catch{setError('บันทึกไม่สำเร็จ อาจมีการแก้ไขจากที่อื่น ข้อมูลในฟอร์มยังอยู่ กรุณาตรวจการเชื่อมต่อหรือนำออกสำรอง');}finally{setBusy(false)}};
 const exportCase=()=>{const blob=new Blob([JSON.stringify(editing,null,2)],{type:'application/json'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download='meq-case.json';a.click();URL.revokeObjectURL(url)};
 const allowed=canWrite && (!editing?.id || previewCases || canApprove || editing.author_id===me);
 if(editing){const d=editing.document,stage=d.stages[active],summary=summarizeMeq(d),warnings=reviewMeq(d);return <>
 <div className="workspace-heading"><div><h2>{editing.title||'สร้างเคส MEQ'}</h2><p>ปีการศึกษา {editing.academic_year} · ปีสอบ {editing.exam_year||'ยังไม่ระบุ'} · {summary.stages} ตอน · {summary.questions} คำถาม</p></div><button className="btn ghost" disabled={busy} onClick={close}>กลับคลัง MEQ</button></div>
 <p className="meq-note">มุมมองผู้จัดทำข้อสอบ ดูทุกตอนได้ · ยังไม่ใช่หน้าสอบจับเวลาสำหรับผู้เข้าสอบ</p>
 {d.sourceReview&&<p className="meq-note">{d.sourceReview}</p>}
 {warnings.length>0&&<div className="editor-confirm"><strong>ต้องตรวจต้นฉบับก่อนนำไปใช้สอบ</strong><ul>{warnings.map(w=><li key={w}>{w}</li>)}</ul></div>}
 {error&&<p className="editor-confirm" role="alert">{error}</p>}
 <fieldset className="editor-fields" disabled={!allowed||busy}>
 <div className="grid3"><Field label="ชื่อเคส / ชุด" value={editing.title} onChange={e=>update({title:e.target.value})}/><Field label="ปีการศึกษา (พ.ศ.)" type="number" value={editing.academic_year} onChange={e=>update({academic_year:e.target.value})}/><Field label="ปีที่สอบ (พ.ศ.)" type="number" value={editing.exam_year||''} onChange={e=>update({exam_year:e.target.value})}/></div>
 <div className="grid2"><div className="field"><label>สาขา</label><select value={d.specialty_id||''} onChange={e=>docUpdate({specialty_id:e.target.value})}><option value="">— เลือก —</option>{bp.specs.map(s=><option key={s.id} value={String(s.id)}>{s.name_th}</option>)}</select></div><Field label="Diagnosis / คำวินิจฉัย" value={d.diagnosis||''} onChange={e=>docUpdate({diagnosis:e.target.value})}/></div>
 <Field label="วัตถุประสงค์ / Competency" area value={d.competency||''} onChange={e=>docUpdate({competency:e.target.value})}/>
 <Field label="คำแนะนำการสอบ" area value={d.instructions||''} onChange={e=>docUpdate({instructions:e.target.value})}/>
 </fieldset>
 <div className="meq-parts"><nav aria-label="ตอนของเคส MEQ">{d.stages.map((s,i)=><button className={'status-filter'+(active===i?' selected':'')} aria-current={active===i?'step':undefined} key={s.id} onClick={()=>setActive(i)}>ตอนที่ {i+1} <span>{s.minutes} นาที</span></button>)}{allowed&&<button className="btn ghost" disabled={busy} onClick={()=>{docUpdate({stages:[...d.stages,newStage()]});setActive(d.stages.length)}}>เพิ่มตอน</button>}</nav>
 <section className="card"><h3>ตอนที่ {active+1}</h3><fieldset className="editor-fields" disabled={!allowed||busy}>
 <div className="grid2"><Field label="ชื่อตอน" value={stage.title} onChange={e=>stageUpdate({title:e.target.value})}/><Field label="เวลาของตอน (นาที)" type="number" min="1" value={stage.minutes} onChange={e=>stageUpdate({minutes:Number(e.target.value)})}/></div>
 <Field label="ข้อมูลผู้ป่วย / ข้อมูลที่เพิ่มในตอนนี้" area value={stage.scenario} onChange={e=>stageUpdate({scenario:e.target.value})}/>
 {stage.questions.map((q,i)=><section className="meq-question" key={q.id}><h3>คำถาม {q.number||i+1}</h3><Field label="คำถาม" area value={q.prompt} onChange={e=>stageUpdate({questions:stage.questions.map(x=>x.id===q.id?{...x,prompt:e.target.value}:x)})}/><Field label="คะแนนเต็มรายคำถาม" type="number" min="0" value={q.points} onChange={e=>stageUpdate({questions:stage.questions.map(x=>x.id===q.id?{...x,points:Number(e.target.value)}:x)})}/><Field label="แนวคำตอบ (สำหรับผู้ตรวจ)" area value={q.modelAnswer||''} onChange={e=>stageUpdate({questions:stage.questions.map(x=>x.id===q.id?{...x,modelAnswer:e.target.value}:x)})}/><Field label="เกณฑ์ให้คะแนน / rubric" area value={q.rubric||''} onChange={e=>stageUpdate({questions:stage.questions.map(x=>x.id===q.id?{...x,rubric:e.target.value}:x)})}/>
<div className="grid2"><div className="field"><label>หมวดหลัก</label><select value={q.nl_domain_code||''} onChange={e=>stageUpdate({questions:stage.questions.map(x=>x.id===q.id?{...x,nl_domain_code:e.target.value,nl_subitem:''}:x)})}><option value="">— เลือก —</option>{bp.domains.map(dm=><option key={dm.code} value={dm.code}>{dm.title}</option>)}</select></div><div className="field"><label>หัวข้อย่อย</label><select value={q.nl_subitem||''} disabled={!q.nl_domain_code} onChange={e=>stageUpdate({questions:stage.questions.map(x=>x.id===q.id?{...x,nl_subitem:e.target.value}:x)})}><option value="">— เลือก —</option>{bp.subitems.filter(s=>s.domain_code===q.nl_domain_code).map(s=><option key={s.id} value={s.name}>{s.name}</option>)}</select></div></div>
<div className="field"><label>ภารกิจแพทย์</label><select value={q.physician_task||''} onChange={e=>stageUpdate({questions:stage.questions.map(x=>x.id===q.id?{...x,physician_task:e.target.value}:x)})}><option value="">— เลือก —</option>{bp.tasks.map(t=><option key={t.code} value={t.code}>{t.name}</option>)}</select></div>
<button className="btn ghost" disabled={stage.questions.length===1} onClick={()=>{if(confirm('ลบคำถามนี้จากฉบับร่าง?'))stageUpdate({questions:stage.questions.filter(x=>x.id!==q.id)})}}>ลบคำถามนี้</button></section>)}
 <button className="btn ghost" onClick={()=>stageUpdate({questions:[...stage.questions,newQuestion()]})}>เพิ่มคำถามในตอนนี้</button>
 <button className="btn ghost" style={{marginLeft:10}} disabled={d.stages.length===1} onClick={()=>{if(confirm('ลบตอนนี้และคำถามภายในจากฉบับร่าง?')){docUpdate({stages:d.stages.filter((_,i)=>i!==active)});setActive(0)}}}>ลบตอนนี้</button>
 </fieldset></section></div>
 <div className="meq-save"><span role="status">{dirty?'ยังไม่ได้บันทึก · ':''}รวม {summary.minutes} นาที · {summary.points} คะแนน</span><div className="row"><button className="btn ghost" onClick={exportCase}>นำออก JSON</button>{allowed&&<button className="btn" disabled={busy} onClick={save}>{busy?'กำลังบันทึก…':previewCases?'บันทึกตัวอย่าง':'บันทึกฉบับร่าง'}</button>}</div></div>
 </>}
 const commitCases=async(list)=>{if(!list.length||list.length>50)throw Error('เลือกไฟล์ที่มี 1–50 เคส');for(const row of list){const problem=validateMeq(row);if(problem)throw Error(problem);if(row.document.version!==1)throw Error('รูปแบบไฟล์ไม่รองรับ');}const payload=list.map(row=>({title:row.title,academic_year:Number(row.academic_year),exam_year:row.exam_year?Number(row.exam_year):null,document:row.document,author_id:me}));if(previewCases)setRows(old=>[...old,...payload.map(row=>({...row,id:crypto.randomUUID()}))]);else{const {error}=await sb.from('meq_cases').insert(payload);if(error)throw Error('นำเข้าไม่สำเร็จ กรุณาตรวจสิทธิ์และลองใหม่');await load();}return payload.length;};
 const importFile=async(event)=>{const file=event.target.files?.[0];event.target.value='';if(!file)return;setBusy(true);setError('');try{const parsed=JSON.parse(await file.text());const n=await commitCases(Array.isArray(parsed)?parsed:[parsed]);notify?.(`นำเข้า ${n} เคสแล้ว`);}catch(e){setError(e.message||'อ่านไฟล์ไม่สำเร็จ');}finally{setBusy(false)}};
 const importMarkdown=async(event)=>{const file=event.target.files?.[0];event.target.value='';if(!file)return;setBusy(true);setError('');try{const cases=parseMeqMarkdown(await file.text());if(!cases.length)throw Error('ไม่พบชุดข้อสอบในไฟล์ — ต้องมีหัวข้อ “# ชุดที่ N”');const n=await commitCases(cases);notify?.(`นำเข้า ${n} ชุดจากไฟล์ Markdown แล้ว`);}catch(e){setError(e.message||'อ่านไฟล์ Markdown ไม่สำเร็จ');}finally{setBusy(false)}};
 const togglePractice=async(r)=>{if(previewCases)return;const next=!r.practice_open;if(!next&&!confirm('ปิดไม่ให้นักศึกษาเข้าถึงเคสนี้ (ทั้งฝึกทำและอ่านทบทวน)?'))return;setBusy(true);setError('');try{const {error}=await sb.rpc('meq_practice_toggle',{_case_id:r.id,_open:next});if(error)throw error;setRows(old=>old.map(x=>x.id===r.id?{...x,practice_open:next}:x));notify?.(next?'เปิดให้นักศึกษาฝึกทำ + อ่านทบทวนแล้ว':'ปิดการเข้าถึงของนักศึกษาแล้ว');}catch(e){setError(e.message||'ทำรายการไม่สำเร็จ');}finally{setBusy(false)}};
 const years=[...new Set(rows.map(r=>r.exam_year).filter(Boolean))].sort((a,b)=>b-a);
 const filtered=rows
   .filter(r=>(r.title+' '+r.academic_year+' '+r.exam_year).includes(search))
   .filter(r=>!fYear||String(r.exam_year)===fYear)
   .filter(r=>!fOpen||(fOpen==='open'?r.practice_open:!r.practice_open))
   .sort((a,b)=>sortBy==='az'?(a.title||'').localeCompare(b.title||'','th'):sortBy==='za'?(b.title||'').localeCompare(a.title||'','th'):new Date(b.updated_at||0)-new Date(a.updated_at||0));
 return <><div className="workspace-heading"><div><h2>คลังข้อสอบ MEQ</h2><p>จัดเก็บเป็นเคส แบ่งตอน พร้อมเวลา คำถาม และเกณฑ์ให้คะแนน</p></div>{canWrite&&<div className="row"><label className="btn ghost" style={{margin:0}}>นำเข้า .md<input className="sr-only" type="file" accept=".md,.markdown,text/markdown,text/plain" disabled={busy} onChange={importMarkdown}/></label><label className="btn ghost" style={{margin:0}}>นำเข้า JSON<input className="sr-only" type="file" accept="application/json,.json" disabled={busy} onChange={importFile}/></label><button className="btn" disabled={busy} onClick={()=>open(newCase())}>สร้างเคส MEQ</button></div>}</div>
 <div className="bank-status"><button className="status-filter" aria-pressed={!legacy} onClick={()=>setLegacy(false)}>เคส MEQ หลายตอน</button><button className="status-filter" aria-pressed={legacy} onClick={()=>setLegacy(true)}>ข้อเขียนเดิม</button></div>
 {legacy?<Bank previewOnly={!!previewCases} sb={sb} bp={bp} me={me} canWrite={canWrite && !previewCases} canApprove={canApprove} notify={notify} bankType="meq"/>:<><p className="meq-note">ปีการศึกษาและปีสอบแยกกัน · ตัวอย่างที่แนบ: ปีการศึกษา 2568 สอบปี 2569</p><div className="row" style={{gap:10,flexWrap:'wrap',alignItems:'flex-end'}}><div style={{flex:'1 1 220px'}}><Field label="ค้นหาชื่อเคสหรือปี" value={search} onChange={e=>setSearch(e.target.value)}/></div><div className="field" style={{flex:'0 0 auto',minWidth:120}}><label>ปีสอบ</label><select value={fYear} onChange={e=>setFYear(e.target.value)}><option value="">ทั้งหมด</option>{years.map(y=><option key={y} value={String(y)}>{y}</option>)}</select></div>{canApprove&&<div className="field" style={{flex:'0 0 auto',minWidth:140}}><label>สถานะเปิดให้ นศ.</label><select value={fOpen} onChange={e=>setFOpen(e.target.value)}><option value="">ทั้งหมด</option><option value="open">🟢 เปิดอยู่</option><option value="closed">⚪ ปิด</option></select></div>}<div className="field" style={{flex:'0 0 auto',minWidth:150}}><label>เรียงตาม</label><select value={sortBy} onChange={e=>setSortBy(e.target.value)}><option value="az">ชื่อ ก→ฮ (A→Z)</option><option value="za">ชื่อ ฮ→ก (Z→A)</option><option value="recent">อัปเดตล่าสุด</option></select></div></div>{error&&<div role="alert" className="editor-confirm">{error} <button className="btn ghost" onClick={load}>ลองใหม่</button></div>}<p className="muted" style={{margin:'6px 0'}}>พบ {filtered.length} ชุด{(search||fYear||fOpen)?<> · <button className="text-action" onClick={()=>{setSearch('');setFYear('');setFOpen('');}}>ล้างตัวกรอง</button></>:''}</p>{loading?<p role="status">กำลังโหลด…</p>:<div className="meq-list">{filtered.map(r=>{const t=summarizeMeq(r.document),w=reviewMeq(r.document);return <div className="meq-case-wrap" key={r.id} style={{display:'flex',flexWrap:'wrap',gap:8,alignItems:'stretch',marginBottom:8}}><button className="meq-case-row" style={{flex:'1 1 320px',marginBottom:0}} onClick={()=>open(r)}><span><strong>{r.title}</strong><small>ปีการศึกษา {r.academic_year} · สอบ {r.exam_year||'—'}</small>{w.length>0&&<small className="meq-warning">มี {w.length} จุดที่ต้องตรวจต้นฉบับ</small>}</span><span>{t.stages} ตอน · {t.questions} คำถาม<br/>{t.minutes} นาที · {t.points} คะแนน</span><span aria-hidden="true">→</span></button>{canApprove&&!previewCases&&<button type="button" className={'btn '+(r.practice_open?'':'ghost')} disabled={busy} title={r.practice_open?'นักศึกษาเข้าถึงได้ (ฝึกทำ + อ่านทบทวน) — กดเพื่อปิด':'ปิดอยู่ — กดเพื่อเปิดให้นักศึกษาฝึกทำและอ่านทบทวน'} onClick={()=>togglePractice(r)} style={{flex:'0 0 auto',alignSelf:'stretch',whiteSpace:'normal',maxWidth:180}}>{r.practice_open?'🟢 เปิดให้ นศ. แล้ว':'⚪ เปิดให้ นศ.'}</button>}</div>})}{!filtered.length&&!error&&<div className="empty">{search?'ไม่พบเคสที่ตรงกับการค้นหา':'ยังไม่มีเคส MEQ หลายตอนในคลัง'}</div>}</div>}</>}
 </>;
}
